# Generated by Django 5.1.7 on 2025-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_picture', models.ImageField(blank=True, upload_to='picture')),
                ('title', models.CharField(max_length=500)),
                ('seasone', models.PositiveIntegerField(blank=True)),
                ('episod', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
