# Generated by Django 5.1.7 on 2025-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeitems',
            name='anime_picture',
            field=models.ImageField(blank=True, upload_to='static/picture'),
        ),
    ]
